version: "3.0"

services:
  node:
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/src/app
      - ./.node_env:/usr/src/app/.env
    links:
      - mongodb
      - minio1
      - minio2
      - minio3
      - minio4

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  ## minio stacks

  minio1:
    image: minio/minio
    volumes:
      - rpm_storage_stack1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: lwzlJgSubYjdbGhYL87jgbwxhXSEAxdA
      MINIO_SECRET_KEY: Gc_Gj4sNAeo5zlSM56xPWa0dLpGaOUD_FtLiUydhKmOTDK15VbZeWb1wl9NwiD1t_phXodwCPDZ1_C4DC_mcAw
    command: server http://minio{1...4}/export

  minio2:
    image: minio/minio
    volumes:
      - rpm_storage_stack2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: lwzlJgSubYjdbGhYL87jgbwxhXSEAxdA
      MINIO_SECRET_KEY: Gc_Gj4sNAeo5zlSM56xPWa0dLpGaOUD_FtLiUydhKmOTDK15VbZeWb1wl9NwiD1t_phXodwCPDZ1_C4DC_mcAw
    command: server http://minio{1...4}/export

  minio3:
    image: minio/minio
    volumes:
      - rpm_storage_stack3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: lwzlJgSubYjdbGhYL87jgbwxhXSEAxdA
      MINIO_SECRET_KEY: Gc_Gj4sNAeo5zlSM56xPWa0dLpGaOUD_FtLiUydhKmOTDK15VbZeWb1wl9NwiD1t_phXodwCPDZ1_C4DC_mcAw
    command: server http://minio{1...4}/export

  minio4:
    image: minio/minio
    volumes:
      - rpm_storage_stack4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: lwzlJgSubYjdbGhYL87jgbwxhXSEAxdA
      MINIO_SECRET_KEY: Gc_Gj4sNAeo5zlSM56xPWa0dLpGaOUD_FtLiUydhKmOTDK15VbZeWb1wl9NwiD1t_phXodwCPDZ1_C4DC_mcAw
    command: server http://minio{1...4}/export

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  rpm_storage_stack1:
  rpm_storage_stack2:
  rpm_storage_stack3:
  rpm_storage_stack4:
